services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: webapp
    container_name: webapp
    command: ["sh", "-c", "cd /app && air -c .air.toml"]
    ports:
      - "8080:8080"
      - "2345:2345" # Debug port
    volumes:
      - .:/app
      - ./tmp:/app/tmp
      - strfkr_go-mod-cache:/home/vscode/go/pkg/mod
      - strfkr_go-build-cache:/home/vscode/.cache/go-build
      - ./data/webapp:/app/data:rw
    environment:
      - DEBUG=true
      - LOG_LEVEL=debug
      - CGO_ENABLED=1
      - DB_PATH=/app/data/webapp.db
      - PORT=8080
      - ENV=development
      - TEMPL_HOT_RELOAD=true
      - HOME=/home/vscode
      - GOCACHE=/home/vscode/.cache/go-build
      - GOPATH=/home/vscode/go
      - GOMODCACHE=/home/vscode/go/pkg/mod
    networks:
      - app-network
    stdin_open: true
    tty: true
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: scraper
    container_name: scraper
    command: ["sh", "-c", "mkdir -p internal/spider/db && sqlc generate -f sqlc.spider.yaml && cd /app && air -c .air-scraper.toml"]
    ports:
      - "8081:8081"
      - "2346:2346" # Debug port
    volumes:
      - .:/app
      - ./tmp:/app/tmp
      - strfkr_go-mod-cache:/home/vscode/go/pkg/mod
      - strfkr_go-build-cache:/home/vscode/.cache/go-build
      - ./data/scraper:/app/data:rw
    environment:
      - DEBUG=true
      - LOG_LEVEL=debug
      - CGO_ENABLED=1
      - DB_PATH=/app/data/scraper.db
      - PORT=8081
      - ENV=development
      - HOME=/home/vscode
      - GOCACHE=/home/vscode/.cache/go-build
      - GOPATH=/home/vscode/go
      - GOMODCACHE=/home/vscode/go/pkg/mod
    networks:
      - app-network
    stdin_open: true
    tty: true
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./web/static:/var/www/static:ro
    environment:
      - NGINX_LOG_LEVEL=debug
    depends_on:
      - webapp
    networks:
      - app-network
volumes:
  strfkr_go-mod-cache:
  strfkr_go-build-cache:
networks:
  app-network:
    driver: bridge
